apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: adaptdljobs.adaptdl.petuum.com
spec:
  group: adaptdl.petuum.com
  scope: Namespaced
  names:
    plural: adaptdljobs
    singular: adaptdljob
    kind: AdaptDLJob
    shortNames:
    - adljob
    - adljobs
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        required: ["spec"]
        properties:
          metadata:
            type: object
            properties:
              # Name is used as label values which have a 63 character limit.
              name:
                type: string
                maxLength: 63
          spec:
            type: object
            required: ["template"]
            properties:
              maxReplicas:
                type: integer
                minimum: 1
              minReplicas:
                type: integer
                minimum: 0
              preemptible:
                type: boolean
              template:
                type: object
                x-kubernetes-preserve-unknown-fields: true
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: Ready
      type: integer
      jsonPath: .status.readyReplicas
    - name: Replicas
      type: string
      jsonPath: .status.replicas
    - name: Restarts
      type: integer
      jsonPath: .status.group
    - name: Status
      type: string
      jsonPath: .status.phase
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
